// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            Pedidos = new HashSet<Pedidos>();
        }

        public int clie_Id { get; set; }
        public string clie_DNI { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_ApellIdos { get; set; }
        public string clie_Sexo { get; set; }
        public string clie_Telefono { get; set; }
        public int? clie_UsuarioCreador { get; set; }
        public DateTime? clie_FechaCreacion { get; set; }
        public int? clie_UsuarioModificador { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
        public bool? clie_Estado { get; set; }

        public virtual tbUsuarios clie_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios clie_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}