// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbDirecciones
    {
        public tbDirecciones()
        {
            Pedidos = new HashSet<Pedidos>();
        }

        public int dire_Id { get; set; }
        public string dire_Descripcion { get; set; }
        public string muni_Id { get; set; }
        public bool? dire_Estado { get; set; }
        public int? dire_UsuarioCreador { get; set; }
        public DateTime? dire_FechaCreacion { get; set; }
        public int? dire_UsuarioModificador { get; set; }
        public DateTime? dire_FechaModificacion { get; set; }

        public virtual tbUsuarios dire_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios dire_UsuarioModificadorNavigation { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}