// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int empl_Id { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombres { get; set; }
        public string empl_Apellidos { get; set; }
        public string empl_Sexo { get; set; }
        public string esci_Id { get; set; }
        public string muni_Id { get; set; }
        public string empl_DireccionExacta { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_Telefono { get; set; }
        public string empl_CorreoElectronico { get; set; }
        public int empl_UsuarioCreador { get; set; }
        public DateTime? empl_FechaCreacion { get; set; }
        public int? empl_UsuarioModificador { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }

        public virtual tbUsuarios empl_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios empl_UsuarioModificadorNavigation { get; set; }
        public virtual tbEstadosCiviles esci { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}