// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public string esci_Id { get; set; }
        public string esci_Descripcion { get; set; }
        public int? esci_UsuarioCreador { get; set; }
        public DateTime? esci_FechaCreacion { get; set; }
        public int? esci_UsuarioModificador { get; set; }
        public DateTime? esci_FechaModificacion { get; set; }

        public virtual tbUsuarios esci_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios esci_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}