// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbEventos
    {
        public tbEventos()
        {
            tbPaquetes_Encabezado = new HashSet<tbPaquetes_Encabezado>();
        }

        public int evnt_Id { get; set; }
        public string evnt_Descri { get; set; }
        public int evnt_UsuarioCreador { get; set; }
        public DateTime? evnt_FechaCreacion { get; set; }
        public int? evnt_UsuarioModificador { get; set; }
        public DateTime? evnt_FechaModificacion { get; set; }
        public bool? evnt_Estado { get; set; }

        public virtual tbUsuarios evnt_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios evnt_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbPaquetes_Encabezado> tbPaquetes_Encabezado { get; set; }
    }
}