// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbFacturas
    {
        public int fact_Id { get; set; }
        public int? pago_id { get; set; }
        public int? pedi_Id { get; set; }
        public int? fact_SubTotal { get; set; }
        public int? fact_Impuesto { get; set; }
        public int? fact_Total { get; set; }
        public int? fact_UsuarioCreador { get; set; }
        public DateTime? fact_FechaCreacion { get; set; }
        public int? fact_UsuarioModificador { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }
        public bool? fact_Estado { get; set; }

        public virtual tbUsuarios fact_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios fact_UsuarioModificadorNavigation { get; set; }
        public virtual tbTipoPago pago { get; set; }
        public virtual Pedidos pedi { get; set; }
    }
}