// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbInventario
    {
        public tbInventario()
        {
            tbPaquete_Detalles = new HashSet<tbPaquete_Detalles>();
        }

        public int inve_Id { get; set; }
        public string inve_Elemento { get; set; }
        public int? inve_Stock { get; set; }
        public int? inve_Precio { get; set; }
        public int inve_UsuarioCreador { get; set; }
        public DateTime? inve_FechaCreacion { get; set; }
        public int? inve_UsuarioModificador { get; set; }
        public DateTime? inve_FechaModificacion { get; set; }
        public bool? inve_Estado { get; set; }

        public virtual tbUsuarios inve_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios inve_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbPaquete_Detalles> tbPaquete_Detalles { get; set; }
    }
}