// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbDirecciones = new HashSet<tbDirecciones>();
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public string muni_Id { get; set; }
        public string muni_Descripcion { get; set; }
        public string dept_Id { get; set; }
        public int? muni_UsuarioCreador { get; set; }
        public DateTime? muni_FechaCreacion { get; set; }
        public int? muni_UsuarioModificador { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }

        public virtual tbDepartamentos dept { get; set; }
        public virtual tbUsuarios muni_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios muni_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbDirecciones> tbDirecciones { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}