// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbPaquetes_Encabezado
    {
        public tbPaquetes_Encabezado()
        {
            tbPaquete_Detalles = new HashSet<tbPaquete_Detalles>();
        }

        public int paqt_Id { get; set; }
        public string paqt_Nombre { get; set; }
        public int? paqt_Precio { get; set; }
        public int? evnt_Id { get; set; }
        public int? paqt_UsuarioCreador { get; set; }
        public DateTime? paqt_FechaCreacion { get; set; }
        public int? paqt_UsuarioModificador { get; set; }
        public DateTime? paqt_FechaModificacion { get; set; }
        public bool? paqt_Estado { get; set; }

        public virtual tbEventos evnt { get; set; }
        public virtual tbUsuarios paqt_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios paqt_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbPaquete_Detalles> tbPaquete_Detalles { get; set; }
    }
}