// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbServicios
    {
        public tbServicios()
        {
            tbPaquete_Detalles = new HashSet<tbPaquete_Detalles>();
        }

        public int serv_Id { get; set; }
        public int? serv_Precio_Nuevo { get; set; }
        public int? prov_Id { get; set; }
        public bool? serv_Estado { get; set; }
        public int? serv_UsuarioCreador { get; set; }
        public DateTime? serv_FechaCreacion { get; set; }
        public int? serv_UsuarioModificador { get; set; }
        public DateTime? serv_FechaModificacion { get; set; }

        public virtual tbProveedores prov { get; set; }
        public virtual tbUsuarios serv_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios serv_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbPaquete_Detalles> tbPaquete_Detalles { get; set; }
    }
}