// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class tbTipoPago
    {
        public tbTipoPago()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int pago_id { get; set; }
        public string pago_Descripcion { get; set; }
        public bool? pago_Estado { get; set; }
        public int? pago_UsuarioCreador { get; set; }
        public DateTime? pago_FechaCreacion { get; set; }
        public int? pago_UsuarioModificador { get; set; }
        public DateTime? pago_FechaModificacion { get; set; }

        public virtual tbUsuarios pago_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios pago_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}