// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_Pedidos_ListarPedidos
    {
        public int pedi_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string dire_Descripcion { get; set; }
        public DateTime? pedi_Inicio { get; set; }
        public DateTime? pedi_Final { get; set; }
    }
}