// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbInventario_ListarInventario
    {
        public int inve_Id { get; set; }
        public string inve_Elemento { get; set; }
        public int? inve_Stock { get; set; }
        public int? inve_Precio { get; set; }
    }
}