// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbTipoPago
    {
        public int pago_id { get; set; }
        public string pago_Descripcion { get; set; }
    }
}