// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbRoles_ListarRoles
    {
        public int role_Id { get; set; }
        public string role_Descripcion { get; set; }
    }
}