// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbPantallas_ListarPantallas
    {
        public int pant_Id { get; set; }
        public string pant_Nombre { get; set; }
    }
}