// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbMunicipios
    {
        public string muni_Id { get; set; }
        public string muni_Descripcion { get; set; }
        public string dept_Descripcion { get; set; }
    }
}