// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbPaqueteDetalles_ListarPaqueteDetalles
    {
        public int pqsv_Id { get; set; }
        public string paqt_Nombre { get; set; }
        public int? serv_Id { get; set; }
        public int? pqsv_Cantidad { get; set; }
    }
}