// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbServicios_ListarServicios
    {
        public int serv_Id { get; set; }
        public string Proveedor { get; set; }
        public string prov_Servicio { get; set; }
        public int? serv_Precio_Nuevo { get; set; }
    }
}