// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbUsuario
    {
        public int usua_Id { get; set; }
        public string usua_Usuario { get; set; }
        public string empleados { get; set; }
        public string role_Descripcion { get; set; }
    }
}