// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbEstadosCiviles
    {
        public string esci_Id { get; set; }
        public string esci_Descripcion { get; set; }
    }
}