// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbClientes_ListarClientes
    {
        public int clie_Id { get; set; }
        public string clie_DNI { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Sexo { get; set; }
        public string clie_Telefono { get; set; }
    }
}