// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbProveedores_ListarProveedores
    {
        public int prov_Id { get; set; }
        public string nombreCompleto { get; set; }
        public string prov_Telefono { get; set; }
        public string prov_Servicio { get; set; }
        public int? prov_Precio { get; set; }
    }
}