// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbPaquetes_Encabezado_ListarPaquetesEncabezado
    {
        public int paqt_Id { get; set; }
        public string paqt_Nombre { get; set; }
        public int? paqt_Precio { get; set; }
    }
}