// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Events_Company_R.Entities.Entities
{
    public partial class VW_tbEmpleados_ListarEmpleados
    {
        public int empl_Id { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombres { get; set; }
        public string empl_sexo { get; set; }
        public string esci_Descripcion { get; set; }
        public string muni_Descripcion { get; set; }
        public string empl_DireccionExacta { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_Telefono { get; set; }
        public string empl_CorreoElectronico { get; set; }
    }
}