// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbFacturas = new HashSet<tbFacturas>();
            tbReservaciones = new HashSet<tbReservaciones>();
        }

        public int clie_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_Identidad { get; set; }
        public string clie_RTN { get; set; }
        public string clie_Sexo { get; set; }
        public string clie_Telefono { get; set; }
        public int clie_UsuCreacion { get; set; }
        public DateTime clie_FechaCreacion { get; set; }
        public int? clie_UsuModificacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
        public bool? clie_Estado { get; set; }

        public virtual tbUsuarios clie_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios clie_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
        public virtual ICollection<tbReservaciones> tbReservaciones { get; set; }
    }
}