// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class tbIngredientesXPlatillos
    {
        public int ingrplat_Id { get; set; }
        public int plat_Id { get; set; }
        public int ingr_Id { get; set; }
        public int ingrplat_Gramos { get; set; }
        public DateTime ingrplat_FechaCreacion { get; set; }
        public int ingrplat_UsuarioCreacion { get; set; }
        public DateTime? ingrplat_FechaModificacion { get; set; }
        public int? ingrplat_UsuarioModificacion { get; set; }
        public bool? ingrplat_Estado { get; set; }

        public virtual tbIngredientes ingr { get; set; }
        public virtual tbUsuarios ingrplat_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios ingrplat_UsuarioModificacionNavigation { get; set; }
        public virtual tbPlatillos plat { get; set; }
    }
}