// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class tbMetodosPago
    {
        public tbMetodosPago()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int metp_Id { get; set; }
        public string metp_Descripcion { get; set; }
        public int metp_UsuCreacion { get; set; }
        public DateTime metp_FechaCreacion { get; set; }
        public int? metp_UsuModificacion { get; set; }
        public DateTime? metp_FechaModificacion { get; set; }
        public bool? metp_Estado { get; set; }

        public virtual tbUsuarios metp_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios metp_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}