// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class tbPlatillos
    {
        public tbPlatillos()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
            tbIngredientesXPlatillos = new HashSet<tbIngredientesXPlatillos>();
        }

        public int plat_Id { get; set; }
        public string plat_Nombre { get; set; }
        public decimal plat_Precio { get; set; }
        public int cate_Id { get; set; }
        public string plat_Imagen { get; set; }
        public DateTime plat_FechaCreacion { get; set; }
        public int plat_UsuarioCreacion { get; set; }
        public DateTime? plat_FechaModificacion { get; set; }
        public int? plat_UsuarioModificacion { get; set; }
        public bool? plat_Estado { get; set; }

        public virtual tbCategorias cate { get; set; }
        public virtual tbUsuarios plat_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios plat_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
        public virtual ICollection<tbIngredientesXPlatillos> tbIngredientesXPlatillos { get; set; }
    }
}