// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class VW_tbProveedores
    {
        public int prov_Id { get; set; }
        public string prov_NombreEmpresa { get; set; }
        public string prov_NombreContacto { get; set; }
        public string prov_Telefono { get; set; }
        public int muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string muni_Codigo { get; set; }
        public int depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public string depa_Codigo { get; set; }
        public string prov_DireccionExacta { get; set; }
        public DateTime prov_FechaCreacion { get; set; }
        public int prov_UsuarioCreacion { get; set; }
        public string user_NombreUsuarioCreacion { get; set; }
        public DateTime? prov_FechaModificacion { get; set; }
        public int? prov_UsuarioModificacion { get; set; }
        public string user_NombreUsuarioModificacion { get; set; }
        public bool prov_Estado { get; set; }
    }
}