// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class VW_tbReservaciones
    {
        public int rese_Id { get; set; }
        public int clie_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_NombreCompleto { get; set; }
        public string clie_RTN { get; set; }
        public string clie_Sexo { get; set; }
        public int sucu_Id { get; set; }
        public string sucu_Nombre { get; set; }
        public int rese_Personas { get; set; }
        public DateTime rese_FechaHora { get; set; }
        public DateTime rese_FechaCreacion { get; set; }
        public int rese_UsuCreacion { get; set; }
        public string user_NombreUsuCreacion { get; set; }
        public DateTime? rese_FechaModificacion { get; set; }
        public int? rese_UsuModificacion { get; set; }
        public string user_NombreUsuModificacion { get; set; }
        public bool rese_Estado { get; set; }
    }
}