// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Restaurante.Entities.Entities
{
    public partial class VW_tbMetodosPago
    {
        public int metp_Id { get; set; }
        public string metp_Descripcion { get; set; }
        public int metp_UsuCreacion { get; set; }
        public string user_NombreUsuarioCreacion { get; set; }
        public DateTime metp_FechaCreacion { get; set; }
        public int? metp_UsuModificacion { get; set; }
        public string user_NombreUsuarioModificacion { get; set; }
        public DateTime? metp_FechaModificacion { get; set; }
        public bool metp_Estado { get; set; }
    }
}